version: "3"

services:
  emily-background-removal-qqei2q:

    image: emily-background-removal-qqei2q
    container_name: emily-background-removal-qqei2q

    build:
      context: ../../
      dockerfile: ./Dockerfile

    env_file:
      - ./.env
    
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}

    ipc: ${IPC}
    runtime: ${RUNTIME}
    networks:
      - emily-background-removal-qqei2q-network

networks:
  emily-background-removal-qqei2q-network:
    driver: bridge
    name: emily-background-removal-qqei2q-network